from __future__ import annotations

from datetime import datetime
import os
import json
from typing import Any, Dict, List, Optional

import anthropic
from loguru import logger
from langchain_core.language_models.llms import LLM
from langchain_core.callbacks.manager import CallbackManagerForLLMRun
from utils.file import _write_to_file


class Claude:  # pylint: disable=too-few-public-methods
    """Thin wrapper around the Claude SDK for a single shot prompt."""

    def __init__(
        self,
        *,
        model_name: str = "claude-3-5-sonnet-20241022",
        temperature: float = 0.1,
        api_key: str = None,
    ) -> None:
        if api_key:
            # Use provided API key
            self._api_key = api_key
        else:
            # Fallback to environment variable
            self._api_key = os.getenv("ANTHROPIC_API_KEY")
            if not self._api_key:
                raise RuntimeError("ANTHROPIC_API_KEY environment variable is not set. Please set it with your Claude API key.")

        # Initialize client with proper configuration
        try:
            self._client = anthropic.Anthropic(api_key=self._api_key)
        except TypeError as e:
            # Fallback for compatibility issues
            logger.warning(f"Failed to initialize Anthropic client with default config: {e}")
            try:
                # Try with minimal configuration
                import httpx
                self._client = anthropic.Anthropic(
                    api_key=api_key,
                    http_client=httpx.Client()
                )
            except Exception as fallback_error:
                logger.error(f"Failed to initialize Anthropic client with fallback config: {fallback_error}")
                raise RuntimeError(f"Failed to initialize Claude client: {fallback_error}")
        
        self._model_name = model_name
        self._temperature = temperature
        logger.info("Claude adapter initialised (model=%s, temperature=%.2f)", model_name, temperature)

    # ------------------------------------------------------------------
    def invoke(self, prompt: str) -> str:
        """Send *prompt* to Claude and return the text response.

        The prompt is logged at DEBUG level (up to 2 000 chars) to make tracing
        easy but avoid overwhelming the logs.
        """
        # logger.debug(f"Claude prompt (first 100000 chars): {prompt[:100000]}")

        try:
            response = self._client.messages.create(
                model=self._model_name,
                max_tokens=32000,  # Increased from 8192 to 25600 for longer responses
                temperature=self._temperature,
                messages=[
                    {
                        "role": "user",
                        "content": prompt
                    }
                ]
            )
            text: str = response.content[0].text if response.content else ""
            # logger.debug(f"Claude raw response: {text[:10000]}")
            return text
        except Exception as exc:  # noqa: BLE001
            logger.error(f"Claude API call failed: {exc}")
            # Bubble up so caller can handle / return error JSON.
            raise 


class LangChainClaude(LLM):
    """LangChain-compatible wrapper around the Claude class."""
    
    model_name: str = "claude-3-5-sonnet-20241022"
    temperature: float = 0.1
        
    def __init__(
        self,
        *,
        model_name: str = "claude-3-5-sonnet-20241022",
        temperature: float = 0.1,
        api_key: str = None,
        **kwargs
    ):
        super().__init__(model_name=model_name, temperature=temperature, **kwargs)
        # Create Claude instance without setting it as a field to avoid Pydantic conflicts
        object.__setattr__(self, '_claude', Claude(model_name=model_name, temperature=temperature, api_key=api_key))

    @property
    def _llm_type(self) -> str:
        """Return identifier of llm type."""
        return "claude"

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        """Call out to Claude's generate endpoint.
        
        Args:
            prompt: The prompt to pass into the model.
            stop: Optional list of stop words to use when generating.
            run_manager: Optional callback manager.
            
        Returns:
            The string generated by the model.
        """
        prompt_file = _write_to_file(prompt, "claude_prompt", "logs/prompts")
        logger.info(f" Prompt saved to: {prompt_file}")

        response = self._claude.invoke(prompt)
        
        # Handle stop words if provided
        if stop:
            for stop_word in stop:
                if stop_word in response:
                    response = response.split(stop_word)[0]
                    break

        response_file = _write_to_file(response, "claude_response", "logs/responses")
        logger.info(f" Response saved to: {response_file}")

        return response

    @property
    def _identifying_params(self) -> Dict[str, Any]:
        """Get the identifying parameters."""
        return {
            "model_name": self.model_name,
            "temperature": self.temperature,
        } 