from __future__ import annotations

from datetime import datetime
import os
import json
from typing import Any, Dict, List, Optional
import time

import openai  # type: ignore
from loguru import logger
from langchain_core.language_models.llms import LLM
from langchain_core.callbacks.manager import CallbackManagerForLLMRun
from utils.file import _write_to_file


class DeepSeek:  # pylint: disable=too-few-public-methods
    """Thin wrapper around the DeepSeek API for a single shot prompt."""

    def __init__(
        self,
        *,
        model_name: str = "deepseek-chat",
        temperature: float = 0.1,
        api_key: str = None,
        timeout: int = 600,  # 10 minutes default timeout
    ) -> None:
        if api_key:
            # Use provided API key
            self._api_key = api_key
        else:
            # Fallback to environment variable
            self._api_key = os.getenv("DEEPSEEK_API_KEY")
            if not self._api_key:
                raise RuntimeError("DEEPSEEK_API_KEY environment variable is not set. Please set it with your DeepSeek API key.")

        # Configure the OpenAI client for DeepSeek
        self._client = openai.OpenAI(
            api_key=self._api_key,
            base_url="https://api.deepseek.com/v1",
        )

        self._generation_cfg: Dict[str, Any] = {
            "temperature": temperature,
            "max_tokens": 8192,  # DeepSeek's maximum token limit
            "model": model_name,
        }
        self.model_name = model_name
        self.timeout = timeout
        logger.info("DeepSeek adapter initialised (model=%s, temperature=%.2f, timeout=%ds)", model_name, temperature, timeout)

    # ------------------------------------------------------------------
    def invoke(self, prompt: str) -> str:
        """Send *prompt* to DeepSeek and return the text response.

        The prompt is logged at DEBUG level (up to 2 000 chars) to make tracing
        easy but avoid overwhelming the logs.
        """
        # logger.debug(f"DeepSeek prompt (first 100000 chars): {prompt[:100000]}")

        try:
            start_time = time.time()
            
            response = self._client.chat.completions.create(
                model=self.model_name,
                messages=[
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=self._generation_cfg["temperature"],
                max_tokens=self._generation_cfg["max_tokens"],
                timeout=self.timeout,
            )
            
            elapsed_time = time.time() - start_time
            if elapsed_time > self.timeout:
                logger.warning(f"DeepSeek API call took {elapsed_time:.2f}s (timeout: {self.timeout}s)")
            
            text: str = response.choices[0].message.content or ""
            # logger.debug(f"DeepSeek raw response: {text[:10000]}")
            return text
        except Exception as exc:  # noqa: BLE001
            logger.error(f"DeepSeek API call failed: {exc}")
            # Bubble up so caller can handle / return error JSON.
            raise 


class LangChainDeepSeek(LLM):
    """LangChain-compatible wrapper around the DeepSeek class."""
    
    model_name: str = "deepseek-chat"
    temperature: float = 0.1
        
    def __init__(
        self,
        *,
        model_name: str = "deepseek-chat",
        temperature: float = 0.1,
        api_key: str = None,
        timeout: int = 600,  # 10 minutes default timeout
        **kwargs
    ):
        super().__init__(model_name=model_name, temperature=temperature, **kwargs)
        # Create DeepSeek instance without setting it as a field to avoid Pydantic conflicts
        object.__setattr__(self, '_deepseek', DeepSeek(model_name=model_name, temperature=temperature, api_key=api_key, timeout=timeout))

    @property
    def _llm_type(self) -> str:
        """Return identifier of llm type."""
        return "deepseek"

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        """Call out to DeepSeek's generate endpoint.
        
        Args:
            prompt: The prompt to pass into the model.
            stop: Optional list of stop words to use when generating.
            run_manager: Optional callback manager.
            
        Returns:
            The string generated by the model.
        """
        prompt_file = _write_to_file(prompt, "deepseek_prompt", "logs/prompts")
        logger.info(f" Prompt saved to: {prompt_file}")

        response = self._deepseek.invoke(prompt)

        
        # Handle stop words if provided
        if stop:
            for stop_word in stop:
                if stop_word in response:
                    response = response.split(stop_word)[0]
                    break

        response_file = _write_to_file(response, "deepseek_response", "logs/responses")
        logger.info(f" Response saved to: {response_file}")

        return response

    @property
    def _identifying_params(self) -> Dict[str, Any]:
        """Get the identifying parameters."""
        return {
            "model_name": self.model_name,
            "temperature": self.temperature,
        }