from __future__ import annotations

from datetime import datetime
import os
import json
from typing import Any, Dict, List, Optional

import requests
from loguru import logger
from langchain_core.language_models.llms import LLM
from langchain_core.callbacks.manager import CallbackManagerForLLMRun
from utils.file import _write_to_file


class Grok:  # pylint: disable=too-few-public-methods
    """Thin wrapper around the Grok API for a single shot prompt."""

    def __init__(
        self,
        *,
        model_name: str = "grok-beta",
        temperature: float = 0.1,
        api_key: str = None,
    ) -> None:
        if api_key:
            # Use provided API key
            self._api_key = api_key
        else:
            # Fallback to environment variable
            self._api_key = os.getenv("GROK_API_KEY")
            if not self._api_key:
                raise RuntimeError("GROK_API_KEY environment variable is not set. Please set it with your Grok API key.")
        self._model_name = model_name
        self._temperature = temperature
        self._base_url = "https://api.x.ai/v1"
        logger.info("Grok adapter initialised (model=%s, temperature=%.2f)", model_name, temperature)

    # ------------------------------------------------------------------
    def invoke(self, prompt: str) -> str:
        """Send *prompt* to Grok and return the text response.

        The prompt is logged at DEBUG level (up to 2 000 chars) to make tracing
        easy but avoid overwhelming the logs.
        """
        # logger.debug(f"Grok prompt (first 100000 chars): {prompt[:100000]}")

        try:
            headers = {
                "Authorization": f"Bearer {self._api_key}",
                "Content-Type": "application/json"
            }
            
            payload = {
                "model": self._model_name,
                "messages": [
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                "temperature": self._temperature,
                "max_tokens": 512000  # Increased from 8192 to 512000 for longer responses
            }
            
            response = requests.post(
                f"{self._base_url}/chat/completions",
                headers=headers,
                json=payload,
                timeout=120  # 2 minute timeout
            )
            
            if response.status_code != 200:
                logger.error(f"Grok API error: {response.status_code} - {response.text}")
                raise Exception(f"Grok API error: {response.status_code} - {response.text}")
            
            response_data = response.json()
            text: str = response_data.get("choices", [{}])[0].get("message", {}).get("content", "")
            # logger.debug(f"Grok raw response: {text[:10000]}")
            return text
            
        except Exception as exc:  # noqa: BLE001
            logger.error(f"Grok API call failed: {exc}")
            # Bubble up so caller can handle / return error JSON.
            raise 


class LangChainGrok(LLM):
    """LangChain-compatible wrapper around the Grok class."""
    
    model_name: str = "grok-beta"
    temperature: float = 0.1
        
    def __init__(
        self,
        *,
        model_name: str = "grok-beta",
        temperature: float = 0.1,
        api_key: str = None,
        **kwargs
    ):
        super().__init__(model_name=model_name, temperature=temperature, **kwargs)
        # Create Grok instance without setting it as a field to avoid Pydantic conflicts
        object.__setattr__(self, '_grok', Grok(model_name=model_name, temperature=temperature, api_key=api_key))

    @property
    def _llm_type(self) -> str:
        """Return identifier of llm type."""
        return "grok"

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        """Call out to Grok's generate endpoint.
        
        Args:
            prompt: The prompt to pass into the model.
            stop: Optional list of stop words to use when generating.
            run_manager: Optional callback manager.
            
        Returns:
            The string generated by the model.
        """
        prompt_file = _write_to_file(prompt, "grok_prompt", "logs/prompts")
        logger.info(f" Prompt saved to: {prompt_file}")

        response = self._grok.invoke(prompt)
        
        # Handle stop words if provided
        if stop:
            for stop_word in stop:
                if stop_word in response:
                    response = response.split(stop_word)[0]
                    break

        response_file = _write_to_file(response, "grok_response", "logs/responses")
        logger.info(f" Response saved to: {response_file}")

        return response

    @property
    def _identifying_params(self) -> Dict[str, Any]:
        """Get the identifying parameters."""
        return {
            "model_name": self.model_name,
            "temperature": self.temperature,
        } 